sidebar:
  - include: ../configs/sidebar/technologies.yml
    include_parser: skill_list
  - name: Education
    icon: university
    include_parser: education
    include: ../configs/sidebar/education.yml
  - name: Certificates
    icon: certificate
    include_parser: certificates
    include: ../configs/sidebar/certificates.yml
#  - name: Extra
#    icon: puzzle-piece
#    include_parser: extra
#    include: ../configs/sidebar/extra.yml
main:
  - name: Experience
    icon: suitcase
    file: ../configs/experience.yml
#  - name: Volunteering
#    icon: hand-sparkles
#    file: ../configs/after/volunteering.yml
#   - name: Projects
#     icon: \faProjectDiagram
#     include_parser: projects
#     include: after/projects.yml
