- name: Spidergraph
  list:
    - name: DevOps
      proficiency: 6.5
    - name: Linux
      proficiency: 8
    - name: Cyber Security
      proficiency: 3
    - name: Programming
      proficiency: 10
    - name: Algorithms
      proficiency: 4
    - name: Data
      proficiency: 8
    - name: LLMs & AI
      proficiency: 5
- name: Programming
  icon: code
  list:
    - name: Python
      proficiency: 9
    - name: SQL
      proficiency: 7
    - name: D
      proficiency: 5
    - name: C/C++
      proficiency: 3
    - name: JavaScript
      proficiency: 2
    - name: Ruby
      proficiency: 1
    - name: Go
      proficiency: 1
- name: Technologies
  icon: cogs
  list:
    - name: Git
      proficiency: 6
    - name: Docker
      proficiency: 7
    - name: HTML
      proficiency: 6
    - name: CSS
      proficiency: 4
    - name: Linux
      proficiency: 8
    - name: RabbitMQ
      proficiency: 6
    #- name: Kubernetes (K8s)
    #  proficiency: 1
- name: Databases
  icon: database
  list:
    - name: PostgreSQL
      proficiency: 7
    - name: Redis
      proficiency: 6
    - name: Supabase
      proficiency: 6
    - name: InfluxDB
      proficiency: 5
- name: Languages
  icon: language
  columns: 1
  list:
    - name: Polish (Native)
      proficiency: 10
      description: C2
    - name: English (Fluent)
      proficiency: 8.5
      description: C1
    - name: Spanish (Basic)
      proficiency: 1
      description: A2
- name: Libraries
  icon: book-open
  cloud:
    - BeautifulSoup4
    - aiohttp
    - SQLAlchemy
    - dataclasses
    - FastAPI
    - FastHTML
- name: Miscellaneous
  icon: tools
  cloud:
    - async
    - REST API
    - WebSockets
    - OSINT
    - OWASP
    - SSH
    #- JSON
    #- YAML
    #- Pandoc
    #- LaTeX
    #- VS Code
    #- Bash
    - nmap
    - Github Actions
    - Code Review
    #- Pre-Commit
    #- Ruff
    - UV
    - Kanban
    - Secure Coding
    - Pytest
    - CI/CD
    - Regex
    - LLM
    - OpenAI
    - AWS/GCP
    - AI Agents
    - Gemini
    #- Prompt Engineering
